In [43]:
import torch
import torch.nn as nn
import torch .nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [44]:
lstm = nn.LSTM(3, 3)
inputs = [torch.randn(1, 3) for _ in range(5)]
inputs

[tensor([[-0.5525,  0.6355, -0.3968]]),
 tensor([[-0.6571, -1.6428,  0.9803]]),
 tensor([[-0.0421, -0.8206,  0.3133]]),
 tensor([[-1.1352,  0.3773, -0.2824]]),
 tensor([[-2.5667, -1.4303,  0.5009]])]

In [45]:
for i in inputs:
    print(i.shape)

torch.Size([1, 3])
torch.Size([1, 3])
torch.Size([1, 3])
torch.Size([1, 3])
torch.Size([1, 3])


In [46]:
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))
hidden[0].shape

torch.Size([1, 1, 3])

In [58]:
for i in inputs:
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print(i.view(1, 1, -1).shape)
out

torch.Size([1, 1, 3])
torch.Size([1, 1, 3])
torch.Size([1, 1, 3])
torch.Size([1, 1, 3])
torch.Size([1, 1, 3])


tensor([[[-0.3600,  0.0892,  0.1867]]], grad_fn=<StackBackward>)

In [48]:
out

tensor([[[-0.3600,  0.0893,  0.0215]]], grad_fn=<StackBackward>)

alternatively do entire sequence all at once

In [49]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
inputs

tensor([[[-0.5525,  0.6355, -0.3968]],

        [[-0.6571, -1.6428,  0.9803]],

        [[-0.0421, -0.8206,  0.3133]],

        [[-1.1352,  0.3773, -0.2824]],

        [[-2.5667, -1.4303,  0.5009]]])

In [50]:
inputs.shape

torch.Size([5, 1, 3])

In [51]:
inputs.shape

torch.Size([5, 1, 3])

- sequence length: 5
- one batch
- feature length: 3

In [52]:
inputs[4][0]

tensor([-2.5667, -1.4303,  0.5009])

In [53]:
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))
hidden

(tensor([[[-0.1473,  0.6272,  1.0935]]]),
 tensor([[[ 0.0939,  1.2381, -1.3459]]]))

In [57]:
out, hidden = lstm(inputs, hidden)
print(out)

tensor([[[-0.1789,  0.1245,  0.0505]],

        [[-0.5324,  0.0689,  0.1008]],

        [[-0.3894,  0.0718,  0.0672]],

        [[-0.1834,  0.0918,  0.0545]],

        [[-0.3598,  0.0892,  0.1844]]], grad_fn=<StackBackward>)
